## 解答

(1) 直線 $l, m$ の方程式と点のパラメータ表示

$l$ は原点 $O(0,0,0)$ と $A(0,-1,1)$ を通るから，方向ベクトルは
$$
\vec{OA} = (0,-1,1)
$$
である．よって $l$ 上の点は実数 $s$ を用いて
$$
P(s) = (0,-s,s)
$$
と表せる．同様に，$Q$ も $l$ 上にあるから
$$
Q(t) = (0,-t,t) \quad (t \in \mathbb{R})
$$
とおく．

直線 $m$ は $B(0,2,1)$ と $C(-2,2,-3)$ を通るので，方向ベクトルは
$$
\vec{BC} = C - B = (-2,2,-3) - (0,2,1) = (-2,0,-4)
$$
である．よって $m$ 上の点 $R$ は実数 $u$ を用いて
$$
R(u) = B + u\,\vec{BC} = (0,2,1) + u(-2,0,-4)
      = (-2u,\,2,\;1-4u)
$$
と表せる．

(2) 正三角形の条件

$\triangle PQR$ が正三角形である条件は
$$
PQ = QR = RP
$$
である．また正三角形の面積を最小にするには，各辺の長さが最小となる場合を考えればよい（正三角形では面積は辺の長さの2乗に比例するからである）．

まず $PQ, PR, QR$ のベクトルを求める．

- $P(0,-s,s),\,Q(0,-t,t)$ より
  $$
  \vec{PQ} = Q - P = (0,-t,t) - (0,-s,s) = (0,\;s-t,\;t-s)
  $$
- $P(0,-s,s),\,R(-2u,2,1-4u)$ より
  $$
  \vec{PR} = R - P = (-2u,\,2 + s,\;1 - 4u - s)
  $$
- $Q(0,-t,t),\,R(-2u,2,1-4u)$ より
  $$
  \vec{QR} = R - Q = (-2u,\,2 + t,\;1 - 4u - t)
  $$

2 点間距離の 2 乗で等しさを表す．

まず
$$
|\vec{PQ}|^2 = 0^2 + (s-t)^2 + (t-s)^2 = 2(s-t)^2
$$

次に
\begin{align*}
|\vec{PR}|^2
&= (-2u)^2 + (2+s)^2 + (1-4u-s)^2 \\
&= 4u^2 + (s^2+4s+4) + \{(1-s)-4u\}^2 \\
&= 4u^2 + s^2+4s+4 + (1-s)^2 -8u(1-s) +16u^2 \\
&= 20u^2 -8u(1-s) + 2s^2 + 2s + 5
\end{align*}

同様に
\begin{align*}
|\vec{QR}|^2
&= (-2u)^2 + (2+t)^2 + (1-4u-t)^2 \\
&= 20u^2 -8u(1-t) + 2t^2 + 2t + 5
\end{align*}

正三角形より
$$
|\vec{PR}|^2 = |\vec{QR}|^2
$$
であるから
\begin{align*}
20u^2 -8u(1-s) + 2s^2 + 2s + 5
&= 20u^2 -8u(1-t) + 2t^2 + 2t + 5
\end{align*}
両辺から $20u^2,5$ を消して整理すると
\begin{align*}
-8u(1-s) + 2s^2 + 2s
&= -8u(1-t) + 2t^2 + 2t
\end{align*}
\begin{align*}
-8u(1-s) + 2s^2 + 2s + 8u(1-t) -2t^2 -2t = 0
\end{align*}
\begin{align*}
8u(s-t) + 2(s^2 - t^2) + 2(s-t) = 0
\end{align*}
\begin{align*}
(s-t)\{8u + 2(s+t) + 2\} = 0
\end{align*}

$\triangle PQR$ は 1 点に潰れてはならないので $P \ne Q$，すなわち $s \ne t$ である．よって
$$
8u + 2(s+t) + 2 = 0
$$
すなわち
$$
4u + s + t + 1 = 0
\qquad\text{(＊)}
$$

次に
$$
|\vec{PQ}|^2 = |\vec{PR}|^2
$$
を用いる．

\begin{align*}
2(s-t)^2 &= 20u^2 -8u(1-s) + 2s^2 + 2s + 5
\end{align*}

左辺を展開すると
$$
2(s-t)^2 = 2(s^2 -2st + t^2) = 2s^2 -4st + 2t^2
$$
よって
\begin{align*}
2s^2 -4st + 2t^2
&= 20u^2 -8u(1-s) + 2s^2 + 2s + 5
\end{align*}
右辺から $2s^2$ を消して
\begin{align*}
-4st + 2t^2
&= 20u^2 -8u(1-s) + 2s + 5
\end{align*}

ここで，(＊) より
$$
s + t = -4u -1
$$
が得られる．これを用いて $s$ を消去する．

まず
$$
s = -4u -1 - t
$$
とおく．

左辺を $t,u$ だけで表す．
\begin{align*}
-4st + 2t^2
&= -4t(-4u -1 - t) + 2t^2 \\
&= 16ut + 4t^2 + 4t^2 + 2t^2 \\
&= 16ut + 10t^2
\end{align*}

右辺も $s = -4u -1 - t$ を代入して
\begin{align*}
20u^2 -8u(1-s) + 2s + 5
&= 20u^2 -8u(1 -(-4u -1 - t)) + 2(-4u -1 - t) + 5\\
&= 20u^2 -8u(1 + 4u + 1 + t) -8u -2 -2t + 5\\
&= 20u^2 -8u(4u + t + 2) -8u +3 -2t\\
&= 20u^2 -32u^2 -8ut -16u -8u +3 -2t\\
&= -12u^2 -8ut -24u +3 -2t
\end{align*}

したがって
\begin{align*}
16ut + 10t^2 &= -12u^2 -8ut -24u +3 -2t
\end{align*}
両辺を整理すると
\begin{align*}
16ut + 10t^2 +12u^2 +8ut +24u -3 +2t &= 0\\
12u^2 +24ut +10t^2 +24u +2t -3 &= 0
\end{align*}

これは $u$ についての 2 次方程式とみなせる．
$$
12u^2 + (24t +24)u + (10t^2 + 2t -3) = 0
$$

この式は後で利用するため，ここでは $t$ をパラメータと見て $u$ を表すのではなく，別の観点から最小条件を考える方が簡単になる．

(3) 座標の位置関係の考察と対称性

直線 $l$ は $z$ 軸方向に対して $(0,-1,1)$ という対角線方向のベクトルを持ち，直線 $m$ は $y=2$ の平面上で，$x,z$ 平面内の直線である．

正三角形 $\triangle PQR$ の辺の長さをできるだけ小さくするためには，おおよそ $P,Q$ は $l$ 上で互いに原点をはさんで対称な位置にあること，また $R$ は $m$ 上でそれと「釣り合う」位置にあることが考えられる．

そこで $P,Q$ が原点に関して対称，すなわち
$$
Q = -P
$$
と仮定してみる．このとき $P = (0,-s,s)$ なら
$$
Q = (0,s,-s)
$$
であり，$l$ 上の表現 $Q(t) = (0,-t,t)$ と比較すると
$$
(0,s,-s) = (0,-t,t)
$$
より $s = -t$ となる．

したがって
$$
t = -s
$$
とおいてよい．

(＊) 式 $4u + s + t + 1 = 0$ に $t=-s$ を代入すると
\begin{align*}
4u + s - s + 1 = 0
\end{align*}
より
$$
u = -\frac{1}{4}
$$

このとき $R$ の座標は
\begin{align*}
R &= R\!\left(-\frac14\right)
= \left(-2\cdot\left(-\frac14\right),\;2,\;1 -4\cdot\left(-\frac14\right)\right)\\
&= \left(\frac12,\;2,\;2\right)
\end{align*}

次に，この $u=-\frac14$ を用いて $|\vec{PQ}|^2 = |\vec{PR}|^2$ から $s$ を求める．

$s+t = 0$ なので
$$
PQ:\;|\vec{PQ}|^2 = 2(s-t)^2 = 2(s -(-s))^2 = 8s^2
$$

$PR$ については
\begin{align*}
\vec{PR}
&= R - P = \left(\frac12,\;2,\;2\right) - (0,-s,s) \\
&= \left(\frac12,\;2+s,\;2-s\right)
\end{align*}
よって
\begin{align*}
|\vec{PR}|^2
&= \left(\frac12\right)^2 + (2+s)^2 + (2-s)^2 \\
&= \frac14 + (s^2+4s+4) + (s^2-4s+4) \\
&= \frac14 + 2s^2 + 8 \\
&= 2s^2 + \frac{33}{4}
\end{align*}

正三角形の条件より
$$
|\vec{PQ}|^2 = |\vec{PR}|^2
$$
すなわち
\begin{align*}
8s^2 &= 2s^2 + \frac{33}{4}\\
6s^2 &= \frac{33}{4}\\
s^2 &= \frac{33}{24} = \frac{11}{8}
\end{align*}
よって
$$
s = \pm\sqrt{\frac{11}{8}} = \pm\frac{\sqrt{22}}{4}
$$
である．

$s$ の符号を変えることは，$P$ と $Q$ を入れ替えることに対応するので，正三角形の形も面積も変わらない．したがって，いずれを採用してもよい．

ここでは
$$
s = \frac{\sqrt{22}}{4},\quad t = -\frac{\sqrt{22}}{4},\quad u = -\frac14
$$
とする．

(4) 点 $P, Q, R$ の座標と最小性

以上より
\begin{align*}
P &= P\!\left(\frac{\sqrt{22}}{4}\right)
= \left(0,\;-\frac{\sqrt{22}}{4},\;\frac{\sqrt{22}}{4}\right),\\[2mm]
Q &= Q\!\left(-\frac{\sqrt{22}}{4}\right)
= \left(0,\;\frac{\sqrt{22}}{4},\;-\frac{\sqrt{22}}{4}\right),\\[2mm]
R &= R\!\left(-\frac14\right)
= \left(\frac12,\;2,\;2\right)
\end{align*}
である．

このときの辺の長さの 2 乗は
\begin{align*}
|\vec{PQ}|^2 &= 8s^2 = 8\cdot\frac{11}{8} = 11
\end{align*}
であり，したがって各辺の長さは $\sqrt{11}$ である．

正三角形の面積 $S$ は，辺の長さを $a$ として
$$
S = \frac{\sqrt{3}}{4}a^2
$$
で表されるから，ここでは
$$
S = \frac{\sqrt{3}}{4}\cdot 11 = \frac{11\sqrt{3}}{4}
$$
である．

一方，$s,t,u$ を変化させるとき，正三角形の辺の長さの 2 乗 $a^2$ は非負の 2 次関数として表され，その最小値は上で求めた解に対応することが分かる（実際，$P$ と $Q$ を原点に関して対称にとることにより，$l$ 上での距離を最小にしつつ，正三角形の条件を満たす $R$ の位置がただ 1 つに決まる）．従って，この配置のときに三角形の面積が最小となる．

よって，$\triangle PQR$ の面積が最小となるときの各点の座標は

$$
P\left(0,\,-\frac{\sqrt{22}}{4},\,\frac{\sqrt{22}}{4}\right),\quad
Q\left(0,\,\frac{\sqrt{22}}{4},\,-\frac{\sqrt{22}}{4}\right),\quad
R\left(\frac12,\,2,\,2\right)
$$

である．