## 解答

(1)  
$f(x)=x^3-3ax^2+bx+c$ とおくと，導関数は

$$
f'(x)=3x^2-6ax+b
$$

である。1次関数 $g(x)$ を

$$
g(x)=px+q
$$

とおく。すべての $x$ で

$$
f(x)=f'(x)g(x)-6x
$$

が成り立つから，

$$
x^3-3ax^2+bx+c=(3x^2-6ax+b)(px+q)-6x
$$

が恒等的に成り立つ。右辺を展開すると

\[
\begin{aligned}
(3x^2-6ax+b)(px+q)
&=3px^3+3qx^2-6apx^2-6aqx+pbx+qbx  \\
&=3px^3+(3q-6ap)x^2+(-6aq+pb)x+qb
\end{aligned}
\]

よって

$$
(3x^2-6ax+b)(px+q)-6x
=3px^3+(3q-6ap)x^2+(-6aq+pb-6)x+qb
$$

である。これが $x^3-3ax^2+bx+c$ に等しいから，係数比較により

\[
\begin{cases}
3p = 1 \\
3q-6ap = -3a \\
-6aq+pb-6 = b \\
qb = c
\end{cases}
\]

が成り立つ。第1式より $p=\dfrac13$。これを第2式に代入すると

\[
3q-6a\cdot \dfrac13 = -3a
\]

すなわち

\[
3q-2a=-3a \quad\Rightarrow\quad 3q=-a \quad\Rightarrow\quad q=-\dfrac a3
\]

となる。次に第3式

\[
-6aq+pb-6=b
\]

に $p=\dfrac13,\ q=-\dfrac a3$ を代入すると，

\[
-6a\left(-\dfrac a3\right)+\dfrac13 b-6=b
\]

すなわち

\[
2a^2+\dfrac13 b-6=b
\]

これを整理して

\[
2a^2-6 = b-\dfrac13 b = \dfrac23 b
\]

ゆえに

\[
b = \dfrac32(2a^2-6)=3(a^2-3)
\]

最後に第4式 $qb=c$ に $q=-\dfrac a3,\ b=3(a^2-3)$ を代入すると

\[
c = -\dfrac a3 \cdot 3(a^2-3) = -a(a^2-3) = -a^3+3a
\]

したがって

$$
b=3(a^2-3),\qquad c=-a^3+3a
$$

である。

(2)  
(1) より

\[
f(x)=x^3-3ax^2+3(a^2-3)x+(-a^3+3a)
\]

である。これを整理して，$x^3$ の変形として眺めるために $x-a$ をくくり出すことを考える。  
まず

\[
\begin{aligned}
f(x)
&=x^3-3ax^2+3a^2x -a^3 +3x-3a \\
&=(x^3-3ax^2+3a^2x-a^3) + (3x-3a) \\
&=(x-a)^3 + 3(x-a)
\end{aligned}
\]

となる。そこで

$$
t=x-a
$$

とおくと

$$
f(x)=t^3+3t
$$

であり，$f(x)=0$ は

$$
t^3+3t=0
$$

と同値である。左辺を因数分解すると

$$
t^3+3t=t(t^2+3)
$$

であるから，

$$
t(t^2+3)=0
$$

となる。$t$ は実数であるから，$t^2+3>0$ が常に成り立つので，$t^2+3=0$ は実数解をもたない。したがって

$$
t=0
$$

のみが実数解である。元の変数に戻すと $t=x-a$ なので

$$
x-a=0 \quad\Rightarrow\quad x=a
$$

ただ 1 個の実数解しか得られない。  
$f(x)=0$ の形は $a$ の値に依らず常に $t^3+3t=0$ と同じ構造をもつので，$a$ をどのように変えても実数解は 1 個にしかならない。

よって，3次方程式 $f(x)=0$ が異なる 3 個の実数解をもつような $a$ の値は存在しない。  

すなわち，求める範囲は存在しない。