## 解答

(1)  
$f(x)=x^3-6x^2-15x+30$ の極値を調べる。

まず導関数を求めると  
$$
f'(x)=3x^2-12x-15
$$
である。極値をとる $x$ は $f'(x)=0$ を満たすので，
$$
3x^2-12x-15=0
$$
より  
$$
x^2-4x-5=0
$$
となる。これを解くと
$$
x=\frac{4\pm\sqrt{16+20}}{2}
=\frac{4\pm\sqrt{36}}{2}
=\frac{4\pm6}{2}
$$
より
$$
x=-1,\ 5
$$
を得る。

次に，極大・極小の判定のために $f''(x)$ を調べる。  
$$
f''(x)=6x-12
$$
であるから，
- $x=-1$ のとき  
  $$
  f''(-1)=6(-1)-12=-18<0
  $$
  となり，$x=-1$ では $f$ は極大値をとる。
- $x=5$ のとき  
  $$
  f''(5)=6\cdot5-12=18>0
  $$
  となり，$x=5$ では $f$ は極小値をとる。

それぞれのときの関数値を求める：
- $x=-1$ のとき
  $$
  f(-1)=(-1)^3-6(-1)^2-15(-1)+30
  =-1-6+15+30
  =38
  $$
  よって極大値は $38$ である。
- $x=5$ のとき
  $$
  f(5)=5^3-6\cdot5^2-15\cdot5+30
  =125-150-75+30
  =-70
  $$
  よって極小値は $-70$ である。

以上より，
- 極大値をとる $x$ は $x=-1$，そのときの極大値は $38$。
- 極小値をとる $x$ は $x=5$，そのときの極小値は $-70$。

---

(2)  
曲線 $C : y=f(x)$ 上の点 $(-3,-6)$ を通り，かつ $C$ に接する直線を求める。

$C$ 上の一般の点を $(t,f(t))$ とおく。この点における接線の方程式は，微分係数 $f'(t)$ を用いて
$$
y-f(t)=f'(t)\,(x-t)
$$
と書ける。これが点 $(-3,-6)$ を通るための条件は，$x=-3,\ y=-6$ を代入して
$$
-6-f(t)=f'(t)\,(-3-t)
$$
が成り立つことである。

ここで，
$$
f(t)=t^3-6t^2-15t+30,
\quad
f'(t)=3t^2-12t-15
$$
であるから，上の条件は
$$
-6-\bigl(t^3-6t^2-15t+30\bigr)
=\bigl(3t^2-12t-15\bigr)\,(-3-t)
$$
となる。

左辺を整理すると
$$
-6-t^3+6t^2+15t-30
=-t^3+6t^2+15t-36
$$
であり，右辺を展開すると
$$
(3t^2-12t-15)(-3-t)
=-(3t^2-12t-15)(t+3)
$$
なので，まず
$$
(3t^2-12t-15)(t+3)
=3t^3+9t^2-12t^2-36t-15t-45
=3t^3-3t^2-51t-45
$$
よって
$$
(3t^2-12t-15)(-3-t)
=-3t^3+3t^2+51t+45
$$
である。

よって方程式は
$$
-t^3+6t^2+15t-36=-3t^3+3t^2+51t+45
$$
となる。両辺を移項して整理すると
$$
(-t^3+6t^2+15t-36)-(-3t^3+3t^2+51t+45)=0
$$
すなわち
$$
2t^3+3t^2-36t-81=0
$$
を得る。

この三次方程式の整数解を調べる。$t=-3$ を代入すると
$$
2(-3)^3+3(-3)^2-36(-3)-81
=-54+27+108-81=0
$$
となるので，$t=-3$ は解である。したがって因数分解すると
$$
2t^3+3t^2-36t-81=(t+3)(2t^2-3t-27)
$$
である。さらに二次式を解くと
$$
2t^2-3t-27=0
$$
より
$$
t=\frac{3\pm\sqrt{9+216}}{4}
=\frac{3\pm\sqrt{225}}{4}
=\frac{3\pm15}{4}
$$
となるので，
$$
t= \frac{3+15}{4}= \frac{18}{4}=\frac{9}{2},\quad
t= \frac{3-15}{4}= \frac{-12}{4}=-3
$$
を得る。したがって
$$
2t^3+3t^2-36t-81=0
$$
の解は $t=-3,\ \dfrac{9}{2}$ である。$t=-3$ は二重解になっているが，接線の条件としては $t=-3,\ \dfrac{9}{2}$ の 2 通りが得られる。

それぞれについて接線の方程式を求める。

1. $t=-3$ のとき  
   傾きは
   $$
   f'(-3)=3(-3)^2-12(-3)-15
   =27+36-15
   =48
   $$
   接点は $(-3,f(-3))$ であり
   $$
   f(-3)=(-3)^3-6(-3)^2-15(-3)+30
   =-27-54+45+30
   =-6
   $$
   よって接線は点 $(-3,-6)$ を通り，傾き $48$ の直線
   $$
   y+6=48(x+3)
   $$
   すなわち
   $$
   y=48x+138
   $$
   である。

2. $t=\dfrac{9}{2}$ のとき  
   傾きを求める：
   $$
   f'\!\left(\frac{9}{2}\right)
   =3\left(\frac{9}{2}\right)^2-12\cdot\frac{9}{2}-15
   =3\cdot\frac{81}{4}-54-15
   =\frac{243}{4}-69
   =\frac{243-276}{4}
   =-\frac{33}{4}
   $$
   接点は
   $$
   \left(\frac{9}{2},\ f\!\left(\frac{9}{2}\right)\right)
   $$
   であるが，接線の式をたてる際には，点 $(-3,-6)$ を通り傾き $-\dfrac{33}{4}$ であればよいので，
   $$
   y+6=-\frac{33}{4}(x+3)
   $$
   と書ける。これを整理すると
   $$
   y=-\frac{33}{4}x-\frac{99}{4}-6
   =-\frac{33}{4}x-\frac{99}{4}-\frac{24}{4}
   =-\frac{33}{4}x-\frac{123}{4}
   $$
   となる。

したがって，求める接線の方程式は
$$
y=48x+138,\qquad
y=-\frac{33}{4}x-\frac{123}{4}
$$
の 2 本である。