## 解答

(1)  
$F$ は点 $B$ から直線 $OA$ に下ろした垂線の足であるから，$\overrightarrow{OF}$ は $\overrightarrow{a}$ に平行である。  
そこで，ある実数 $t$ を用いて
$$
\overrightarrow{OF}=t\overrightarrow{a}
$$
とおく。

また，$F$ は直線 $OA$ 上にあり，$BF\perp OA$ であるから
$$
\overrightarrow{BF}\cdot\overrightarrow{a}=0
$$
が成り立つ。$\overrightarrow{BF}=\overrightarrow{OF}-\overrightarrow{OB}=t\overrightarrow{a}-\overrightarrow{b}$ より，
$$
(t\overrightarrow{a}-\overrightarrow{b})\cdot\overrightarrow{a}=0
$$
すなわち
$$
t|\overrightarrow{a}|^2-\overrightarrow{b}\cdot\overrightarrow{a}=0
$$
となる。ここで $|\overrightarrow{a}|=4$，$\overrightarrow{a}\cdot\overrightarrow{b}=6$ より
$$
t\cdot 16-6=0
$$
したがって
$$
t=\frac{6}{16}=\frac{3}{8}
$$
となる。よって
$$
\overrightarrow{OF}=\frac{3}{8}\overrightarrow{a}
$$
である。

(2)  
点 $D$ は辺 $AB$ を $2:1$ に内分する点であり，$AD:DB=2:1$ であるから，  
内分点のベクトル表示より
$$
\overrightarrow{OD}
=\frac{1\cdot\overrightarrow{A}+2\cdot\overrightarrow{B}}{1+2}
=\frac{\overrightarrow{a}+2\overrightarrow{b}}{3}
$$
となる。

また，点 $E$ は直線 $OA$ に関して点 $D$ と対称な点であるから，$OA$ が線分 $DE$ の垂直二等分線となる。すなわち，$DE$ の中点は直線 $OA$ 上にあり，$DE$ は直線 $OA$ に垂直である。  
まず中点の条件から，点 $M$ を $DE$ の中点とすると
$$
\overrightarrow{OM}=\frac{\overrightarrow{OD}+\overrightarrow{OE}}{2}
$$
であり，$M$ は直線 $OA$ 上にあるので，ある実数 $s$ を用いて
$$
\overrightarrow{OM}=s\overrightarrow{a}
$$
とかける。よって
$$
\frac{\overrightarrow{OD}+\overrightarrow{OE}}{2}=s\overrightarrow{a}
$$
すなわち
$$
\overrightarrow{OE}=2s\overrightarrow{a}-\overrightarrow{OD}
=2s\overrightarrow{a}-\frac{\overrightarrow{a}+2\overrightarrow{b}}{3}
$$
となる。

次に $DE\perp OA$ より
$$
\overrightarrow{DE}\cdot\overrightarrow{a}=0
$$
が成り立つ。$\overrightarrow{DE}=\overrightarrow{OE}-\overrightarrow{OD}$ だから
$$
(\overrightarrow{OE}-\overrightarrow{OD})\cdot\overrightarrow{a}=0
$$
すなわち
$$
\overrightarrow{OE}\cdot\overrightarrow{a}=\overrightarrow{OD}\cdot\overrightarrow{a}
$$
である。ここで
$$
\overrightarrow{OD}=\frac{\overrightarrow{a}+2\overrightarrow{b}}{3}
$$
より
$$
\overrightarrow{OD}\cdot\overrightarrow{a}
=\frac{1}{3}(\overrightarrow{a}\cdot\overrightarrow{a}+2\overrightarrow{b}\cdot\overrightarrow{a})
=\frac{1}{3}(16+2\cdot6)
=\frac{1}{3}\cdot28
=\frac{28}{3}
$$
となる。

一方，$\overrightarrow{OE}=2s\overrightarrow{a}-\dfrac{\overrightarrow{a}+2\overrightarrow{b}}{3}$ なので
$$
\overrightarrow{OE}\cdot\overrightarrow{a}
=\left(2s\overrightarrow{a}-\frac{\overrightarrow{a}+2\overrightarrow{b}}{3}\right)\cdot\overrightarrow{a}
=2s|\overrightarrow{a}|^2-\frac{1}{3}(\overrightarrow{a}+2\overrightarrow{b})\cdot\overrightarrow{a}
$$
$$
=2s\cdot16-\frac{1}{3}(16+2\cdot6)
=32s-\frac{28}{3}
$$
となる。これが $\dfrac{28}{3}$ に等しいから
$$
32s-\frac{28}{3}=\frac{28}{3}
$$
より
$$
32s=\frac{56}{3}
\quad\Rightarrow\quad
s=\frac{56}{3\cdot32}=\frac{7}{12}
$$
である。したがって
$$
\overrightarrow{OM}=s\overrightarrow{a}=\frac{7}{12}\overrightarrow{a}
$$
であり，
$$
\overrightarrow{OE}=2\overrightarrow{OM}-\overrightarrow{OD}
=2\cdot\frac{7}{12}\overrightarrow{a}-\frac{\overrightarrow{a}+2\overrightarrow{b}}{3}
$$
$$
=\frac{7}{6}\overrightarrow{a}-\frac{1}{3}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}
=\left(\frac{7}{6}-\frac{1}{3}\right)\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}
=\frac{5}{6}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}
$$
となる。よって
$$
\overrightarrow{OE}=\frac{5}{6}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}
$$
である。

(3)  
(1)，(2) より
$$
\overrightarrow{OF}=\frac{3}{8}\overrightarrow{a},\quad
\overrightarrow{OE}=\frac{5}{6}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}
$$
である。与えられた条件 $9|\overrightarrow{OE}|=20|\overrightarrow{OF}|$ を用いる。

まず，両辺を 2 乗すると
$$
81|\overrightarrow{OE}|^2=400|\overrightarrow{OF}|^2
$$
となる。

$\overrightarrow{OF}=\dfrac{3}{8}\overrightarrow{a}$ より
$$
|\overrightarrow{OF}|^2=\left|\frac{3}{8}\overrightarrow{a}\right|^2
=\left(\frac{3}{8}\right)^2|\overrightarrow{a}|^2
=\frac{9}{64}\cdot16
=\frac{9}{4}
$$
である。

次に $\overrightarrow{OE}=\dfrac{5}{6}\overrightarrow{a}-\dfrac{2}{3}\overrightarrow{b}$ について
$$
|\overrightarrow{OE}|^2
=\left(\frac{5}{6}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}\right)\cdot
 \left(\frac{5}{6}\overrightarrow{a}-\frac{2}{3}\overrightarrow{b}\right)
$$
$$
=\left(\frac{5}{6}\right)^2|\overrightarrow{a}|^2
-2\cdot\frac{5}{6}\cdot\frac{2}{3}(\overrightarrow{a}\cdot\overrightarrow{b})
+\left(\frac{2}{3}\right)^2|\overrightarrow{b}|^2
$$
と展開できる。ここで $|\overrightarrow{a}|=4$，$\overrightarrow{a}\cdot\overrightarrow{b}=6$ を代入すると
$$
|\overrightarrow{OE}|^2
=\frac{25}{36}\cdot16
-2\cdot\frac{5}{6}\cdot\frac{2}{3}\cdot6
+\frac{4}{9}|\overrightarrow{b}|^2
$$
$$
=\frac{400}{36}
-2\cdot\frac{10}{18}\cdot6
+\frac{4}{9}|\overrightarrow{b}|^2
$$
$$
=\frac{100}{9}-2\cdot\frac{10}{3}+\frac{4}{9}|\overrightarrow{b}|^2
=\frac{100}{9}-\frac{20}{3}+\frac{4}{9}|\overrightarrow{b}|^2
$$
$$
=\frac{100}{9}-\frac{60}{9}+\frac{4}{9}|\overrightarrow{b}|^2
=\frac{40}{9}+\frac{4}{9}|\overrightarrow{b}|^2
$$
となる。

したがって
$$
81|\overrightarrow{OE}|^2
=81\left(\frac{40}{9}+\frac{4}{9}|\overrightarrow{b}|^2\right)
=9\cdot40+9\cdot4|\overrightarrow{b}|^2
=360+36|\overrightarrow{b}|^2
$$
である。一方
$$
400|\overrightarrow{OF}|^2
=400\cdot\frac{9}{4}
=100\cdot9
=900
$$
であるから，
$$
360+36|\overrightarrow{b}|^2=900
$$
となる。これを解くと
$$
36|\overrightarrow{b}|^2=540
\quad\Rightarrow\quad
|\overrightarrow{b}|^2=\frac{540}{36}=15
$$
ゆえに
$$
|\overrightarrow{b}|=\sqrt{15}
$$
となる。