## 解答

(1)  

与式の右辺を展開して左辺に一致することを示す。

まず，複素数の基本的な性質として
$$
|u|^2 = u\overline{u},\quad
|u-v|^2 = (u-v)(\overline{u}-\overline{v})
$$
を用いる。

右辺第2項について，
$$
|z_1\overline{w_2}-z_2\overline{w_1}|^2
= (z_1\overline{w_2}-z_2\overline{w_1})(\overline{z_1}w_2-\overline{z_2}w_1)
$$
であるから，これを展開すると
\[
\begin{aligned}
&|z_1\overline{w_2}-z_2\overline{w_1}|^2 \\
&= z_1\overline{w_2}\,\overline{z_1}w_2
   - z_1\overline{w_2}\,\overline{z_2}w_1
   - z_2\overline{w_1}\,\overline{z_1}w_2
   + z_2\overline{w_1}\,\overline{z_2}w_1 \\
&= |z_1|^2|w_2|^2 + |z_2|^2|w_1|^2
   - z_1\overline{z_2}\,\overline{w_2}w_1
   - z_2\overline{z_1}\,\overline{w_1}w_2.
\end{aligned}
\]

一方，
\[
\begin{aligned}
({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
&= |z_1|^2|w_1|^2 + |z_1|^2|w_2|^2 \\
&\quad + |z_2|^2|w_1|^2 + |z_2|^2|w_2|^2.
\end{aligned}
\]

したがって右辺全体は
\[
\begin{aligned}
&({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
- |z_1\overline{w_2}-z_2\overline{w_1}|^2 \\
&= \bigl(|z_1|^2|w_1|^2 + |z_1|^2|w_2|^2
        + |z_2|^2|w_1|^2 + |z_2|^2|w_2|^2\bigr)\\
&\quad -\bigl(|z_1|^2|w_2|^2 + |z_2|^2|w_1|^2
  - z_1\overline{z_2}\,\overline{w_2}w_1
  - z_2\overline{z_1}\,\overline{w_1}w_2\bigr) \\
&= |z_1|^2|w_1|^2 + |z_2|^2|w_2|^2
   + z_1\overline{z_2}\,\overline{w_2}w_1
   + z_2\overline{z_1}\,\overline{w_1}w_2.
\end{aligned}
\]

ここで
$$
z_1\overline{z_2}\,\overline{w_2}w_1
= (z_1w_1)(\overline{z_2w_2}),\quad
z_2\overline{z_1}\,\overline{w_1}w_2
= (z_2w_2)(\overline{z_1w_1})
$$
に注意すると，
\[
\begin{aligned}
&|z_1|^2|w_1|^2 + |z_2|^2|w_2|^2
   + (z_1w_1)(\overline{z_2w_2})
   + (z_2w_2)(\overline{z_1w_1}) \\
&= (z_1w_1)(\overline{z_1w_1})
 + (z_2w_2)(\overline{z_2w_2})
 + (z_1w_1)(\overline{z_2w_2})
 + (z_2w_2)(\overline{z_1w_1}) \\
&= (z_1w_1+z_2w_2)\,\overline{(z_1w_1+z_2w_2)} \\
&= |z_1w_1+z_2w_2|^2.
\end{aligned}
\]

ゆえに
$$
{|z_1w_1+z_2w_2|}^2
=({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
-{|z_1\overline{w_2}-z_2\overline{w_1}|}^2
$$
が成り立つ。

---

(2)  

(1) の結果を用いる。(1) より
$$
|z_1w_1+z_2w_2|^2
=({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
-|z_1\overline{w_2}-z_2\overline{w_1}|^2
$$
であるが，条件 \ding{"AC} より
$$
|z_1w_1+z_2w_2|^2
=({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
$$
だから，両式を比べて
$$
|z_1\overline{w_2}-z_2\overline{w_1}|^2=0
$$
すなわち
$$
z_1\overline{w_2}-z_2\overline{w_1}=0
$$
が従う。よって
$$
z_1\overline{w_2}=z_2\overline{w_1}
$$
である。

ここで，条件 \ding{"AD} より $|z_1|=|w_1|$ だから，$z_1\neq 0,\ w_1\neq 0$ であり，
$$
\frac{z_1}{w_1} = \frac{\overline{w_2}}{\overline{z_2}}
$$
と書ける。右辺を共役を用いて変形すると，
$$
\frac{\overline{w_2}}{\overline{z_2}}
= \overline{\frac{w_2}{z_2}}
$$
である。さらに，$|z_1|=|w_1|$ より
$$
\left|\frac{z_1}{w_1}\right|=\frac{|z_1|}{|w_1|}=1
$$
だから，複素数 $\dfrac{z_1}{w_1}$ は絶対値 1 の複素数である。絶対値 1 の複素数 $u$ については
$$
\overline{u}=\frac{1}{u}
$$
が成り立つので，
$$
\frac{z_1}{w_1}
= \overline{\frac{w_2}{z_2}}
= \frac{1}{\frac{w_2}{z_2}}
= \frac{z_2}{w_2}
$$
を得る。よって
$$
\frac{z_1 - w_1}{z_2 - w_2}
= \frac{z_1/w_1 - 1}{z_2/w_2 - 1}
= \frac{z_2/w_2 - 1}{z_2/w_2 - 1}
= 1
$$
となる。ただし，$z_2\neq w_2$ である（$C$ と $D$ は異なる点）から，分母は 0 ではない。

したがって
$$
\frac{z_1 - w_1}{z_2 - w_2}=1
$$
は実数である。複素数平面において，2点 $P(a)$，$Q(b)$ を結ぶ直線の傾きは $b-a$ の比を考えたときの複素数の偏角に対応し，2直線 $AB, CD$ が平行であることは
$$
\frac{z_1-w_1}{z_2-w_2}\in\mathbb{R}
$$
で表される（2つのベクトルが実数倍の関係にあることに対応する）から，この結果より直線 $AB$ と $CD$ は平行である。

---

(3)  

(2) より，条件 \ding{"AC}，\ding{"AD} のもとで直線 $AB$ と $CD$ は平行である。さらに，$A,B,C,D$ が同一直線上にないことから，$AB$ と $CD$ は異なる平行な直線である。

ここで $AB$ の中点を $M$，$CD$ の中点を $N$ とする。複素数を用いると
$$
M\left(\frac{z_1+w_1}{2}\right),\quad
N\left(\frac{z_2+w_2}{2}\right)
$$
である。

まず，条件 \ding{"AD} より $|z_1|=|w_1|$ であるから，原点 $O(0)$ は線分 $AB$ の垂直二等分線上にある。すなわち，直線 $OM$ は $AB$ と垂直である。同様に，(1) と (2) と全く同様の議論を $z_2,w_2$ について適用すると，$|z_2|=|w_2|$ も従い（後で示す），原点 $O$ は線分 $CD$ の垂直二等分線上にもあるので，直線 $ON$ は $CD$ と垂直となる。

ところが，(2) で示したように $AB$ は $CD$ と平行なので，$AB\perp OM$ かつ $CD\perp ON$ であることから，$OM$ と $ON$ は同一直線上にある。よって $O,M,N$ は一直線上にある。

ここで，先に用いた $|z_2|=|w_2|$ を導いておく。  
(1) の式を $z_1,z_2$ と $w_1,w_2$ を入れ替えて用いると
$$
{|z_1w_1+z_2w_2|}^2
=({|w_1|}^2+{|w_2|}^2)({|z_1|}^2+{|z_2|}^2)
-{|w_1\overline{z_2}-w_2\overline{z_1}|}^2
$$
であるが，左辺および第1項は対称だから
$$
{|z_1w_1+z_2w_2|}^2
=({|z_1|}^2+{|z_2|}^2)({|w_1|}^2+{|w_2|}^2)
$$
と合わせると
$$
|w_1\overline{z_2}-w_2\overline{z_1}|^2=0
$$
すなわち
$$
w_1\overline{z_2}=w_2\overline{z_1}
$$
が従う。これと $z_1\overline{w_2}=z_2\overline{w_1}$ を比べると
$$
z_1\overline{w_2}=z_2\overline{w_1}
,\quad
\overline{z_1}w_2=\overline{z_2}w_1
$$
となり，両辺の積をとると
$$
|z_1|^2|w_2|^2=|z_2|^2|w_1|^2
$$
である。ここで $|z_1|=|w_1|$ なので
$$
|z_1|^2|w_2|^2=|z_1|^2|z_2|^2
$$
となり，$z_1\neq 0$ だから
$$
|w_2|^2=|z_2|^2
$$
すなわち $|w_2|=|z_2|$ が得られる。

したがって $A,B$ も $C,D$ も原点からの距離が等しい 2 点であり，原点はそれぞれの線分の垂直二等分線上にあるから，$OM$ と $ON$ は垂直二等分線として $AB,CD$ の共通の垂直二等分線である。ゆえに $M,N,O$ は一直線上にある。

ここまでで，
- $AB$ と $CD$ は平行
- $M$ と $N$ は一直線 $ON$ 上にある

が分かった。従って，直線 $ON$ についての対称移動を考えると，
- $A$ と $B$ は $ON$ に関して互いに対称
- $C$ と $D$ も $ON$ に関して互いに対称

である。すなわち，直線 $ON$ を対称軸として，4点 $A,B,C,D$ は対称な位置関係にある。

以上より，4点 $A,B,C,D$ はある直線（ここでは $ON$）に関して対称な四角形の頂点となる。