## 解答

(1)  
放物線 $C:y=-\dfrac{1}{2}x^2$ の接線の傾きを求めるために，まず微分を行う。

関数 $y=-\dfrac{1}{2}x^2$ を $x$ で微分すると，
$$
\frac{dy}{dx}=-x
$$
したがって，放物線上の点 $(t,-\dfrac12 t^2)$ における接線の傾きは $-t$ である。

いま，2本の接線 $l_1,l_2$ が点 $P(a,b)$ を通り，それぞれ放物線の点 $Q_1(t_1,-\dfrac12 t_1^2)$，$Q_2(t_2,-\dfrac12 t_2^2)$ における接線とする。  
このとき $l_1,l_2$ の傾きはそれぞれ
$$
m_1=-t_1,\quad m_2=-t_2
$$
である。

接線 $l_1,l_2$ は点 $P$ を通り，かつ放物線の接線であるから，接線の方程式を用いると，
$Q_1(t_1,-\dfrac12 t_1^2)$ における接線は
$$
y=-\frac12 t_1^2+(-t_1)(x-t_1)
$$
である。ここに $P(a,b)$ が乗るので
$$
b=-\frac12 t_1^2-t_1(a-t_1)=-t_1a+\frac12 t_1^2
$$
同様に $Q_2$ に対して
$$
b=-t_2a+\frac12 t_2^2
$$
よって
$$
-t_1a+\frac12 t_1^2=-t_2a+\frac12 t_2^2
$$
を整理すると
$$
(t_1-t_2)\left(\frac12(t_1+t_2)-a\right)=0
$$
$t_1\neq t_2$ なので
$$
\frac12(t_1+t_2)-a=0 \quad\Rightarrow\quad t_1+t_2=2a
$$

一方，2直線 $l_1,l_2$ は直交するから，傾きの積が $-1$ となる。したがって
$$
m_1m_2=(-t_1)(-t_2)=t_1t_2=-1
$$

以上より $t_1,t_2$ は
$$
t_1+t_2=2a,\quad t_1t_2=-1
$$
を満たす。よって $t_1,t_2$ は
$$
x^2-(t_1+t_2)x+t_1t_2=0
$$
すなわち
$$
x^2-2ax-1=0
$$
の2つの解である。

ゆえに，$l_1,l_2$ の傾き $m_1,m_2$ は $m_1>m_2$ であることに注意して
$$
m_1=-\frac{1}{2}\Bigl((t_1+t_2)+|t_1-t_2|\Bigr),
\quad
m_2=-\frac{1}{2}\Bigl((t_1+t_2)-|t_1-t_2|\Bigr)
$$
と書くこともできるが，和と積を用いると，
$$
m_1+m_2=-(t_1+t_2)=-2a,\quad m_1m_2=t_1t_2=-1
$$
である。よって，$m_1,m_2$ は
$$
x^2+2ax-1=0
$$
の2つの解であり，
$$
m_1=-a+\sqrt{a^2+1},\quad m_2=-a-\sqrt{a^2+1}
$$
と求まる。

（$m_1>m_2$ なので，大きい方を $-a+\sqrt{a^2+1}$ とした。）

---

(2)  
放物線 $C$ と $l_1,l_2$ の接点をそれぞれ $Q_1,Q_2$ とする。  
(1) ですでに用いた記号をそのまま使い，$Q_1(t_1,-\dfrac12 t_1^2)$，$Q_2(t_2,-\dfrac12 t_2^2)$ とおく。

点 $P$ の座標はまだ未知であるが，(1) で得た関係式から $P$ の座標を $t_1,t_2$ で表す。

接線 $Q_1$ での式
$$
b=-t_1a+\frac12 t_1^2
$$
と $t_1+t_2=2a$ から $a=\dfrac{t_1+t_2}{2}$ を代入すると
$$
b=-t_1\cdot\frac{t_1+t_2}{2}+\frac12 t_1^2
 =\frac12(-t_1^2-t_1t_2+t_1^2)
 =-\frac12 t_1t_2
$$
である。同様に $Q_2$ からも同じ式が得られるので矛盾はない。

さらに $t_1t_2=-1$ であったから
$$
b=-\frac12(-1)=\frac12
$$
よって
$$
a=\frac{t_1+t_2}{2},\quad b=\frac12
$$
したがって，点 $P$ の $y$ 座標は常に $\dfrac12$ である。

続いて三角形 $\triangle PQ_1Q_2$ の面積を求める。面積公式として，3点 $(x_1,y_1),(x_2,y_2),(x_3,y_3)$ に対し
$$
\text{面積}=\frac12\left|x_2x_3(y_2-y_3)+\dots\right|
$$
を用いてもよいが，ここではベクトルを用いる。

ベクトル
$$
\overrightarrow{PQ_1}=(t_1-a,\,-\frac12 t_1^2-\frac12),
\quad
\overrightarrow{PQ_2}=(t_2-a,\,-\frac12 t_2^2-\frac12)
$$
であり，三角形の面積は
$$
S=\frac12\,|\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}|
$$
となる。2次元ベクトル $(x_1,y_1),(x_2,y_2)$ の外積の大きさは
$$
|x_1y_2-x_2y_1|
$$
であるから，
$$
\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}
=(t_1-a)\left(-\frac12 t_2^2-\frac12\right)
 -(t_2-a)\left(-\frac12 t_1^2-\frac12\right)
$$

これを計算する。まず展開して
\begin{align\*}
\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}
&=-\frac12(t_1-a)(t_2^2+1)+\frac12(t_2-a)(t_1^2+1)\\
&=\frac12\{(t_2-a)(t_1^2+1)-(t_1-a)(t_2^2+1)\}
\end{align\*}
括弧内を整理する。
\begin{align\*}
&(t_2-a)(t_1^2+1)-(t_1-a)(t_2^2+1)\\
&=t_2t_1^2+t_2-at_1^2-a
 -(t_1t_2^2+t_1-at_2^2-a)\\
&=t_2t_1^2+t_2-at_1^2-a-t_1t_2^2-t_1+at_2^2+a\\
&=t_1^2t_2-t_1t_2^2+t_2-t_1-a(t_1^2-t_2^2)
\end{align\*}
ここで $t_1t_2=-1$，$a=\dfrac{t_1+t_2}{2}$ を用いる。

まず
$$
t_1^2t_2-t_1t_2^2=t_1t_2(t_1-t_2)=-1\cdot(t_1-t_2)=-(t_1-t_2)
$$
また
$$
t_2-t_1=-(t_1-t_2)
$$
なので
$$
t_1^2t_2-t_1t_2^2+t_2-t_1=-(t_1-t_2)-(t_1-t_2)=-2(t_1-t_2)
$$
次に
$$
t_1^2-t_2^2=(t_1-t_2)(t_1+t_2)
$$
よって
$$
-a(t_1^2-t_2^2)
=-\frac{t_1+t_2}{2}\cdot (t_1-t_2)(t_1+t_2)
=-\frac12(t_1-t_2)(t_1+t_2)^2
$$
したがって全体として
$$
(t_2-a)(t_1^2+1)-(t_1-a)(t_2^2+1)
=(t_1-t_2)\left\{-2-\frac12(t_1+t_2)^2\right\}
$$
ゆえに
$$
\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}
=\frac12(t_1-t_2)\left\{-2-\frac12(t_1+t_2)^2\right\}
$$
ここで
$$
t_1+t_2=2a
$$
なので
$$
-2-\frac12(t_1+t_2)^2
=-2-\frac12(2a)^2
=-2-2a^2=-2(a^2+1)
$$
を代入すると
$$
\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}
=\frac12(t_1-t_2)\{-2(a^2+1)\}
=-(a^2+1)(t_1-t_2)
$$
したがって
$$
S=\frac12|\overrightarrow{PQ_1}\times\overrightarrow{PQ_2}|
=\frac12|(a^2+1)(t_1-t_2)|
=\frac12(a^2+1)|t_1-t_2|
$$

ここで，$t_1,t_2$ は $x^2-2ax-1=0$ の解であったから，2解の差は
$$
t_1-t_2=\sqrt{(t_1+t_2)^2-4t_1t_2}
=\sqrt{(2a)^2-4(-1)}
=\sqrt{4a^2+4}=2\sqrt{a^2+1}
$$
となる。よって
$$
|t_1-t_2|=2\sqrt{a^2+1}
$$
であり，三角形の面積は
$$
S=\frac12(a^2+1)\cdot 2\sqrt{a^2+1}
=(a^2+1)\sqrt{a^2+1}
=\left(a^2+1\right)^{\frac32}
$$

条件より $S=8$ だから
$$
\left(a^2+1\right)^{\frac32}=8
$$
両辺を $2/3$ 乗すると
$$
a^2+1=8^{\frac23}
$$
$8=2^3$ より $8^{2/3}=2^2=4$ なので
$$
a^2+1=4\quad\Rightarrow\quad a^2=3
$$
したがって
$$
a=\pm\sqrt{3}
$$

(1) より，対応する点 $P$ の座標は $y$ 座標が常に $\dfrac12$ であることがわかっているから，
$$
P\left(\sqrt{3},\frac12\right),\quad P\left(-\sqrt{3},\frac12\right)
$$
の2点が条件を満たす。

以上より，求める点 $P$ の座標は
$$
\left(\sqrt{3},\frac12\right),\ \left(-\sqrt{3},\frac12\right)
$$
である。