## 解答

(1)  
ベクトルを用いて表すと，
$$
\overrightarrow{AP}=(x-a,\,y,\, -b),\quad
\overrightarrow{AO}=(-a,\,0,\,-b)
$$
である．

平面$\alpha$は点$O$を通り直線$AP$と垂直なので，その法線ベクトルは$\overrightarrow{AP}$である．  
よって，平面$\alpha$は
$$
(x-a,\,y,\,-b)\cdot (X,\,Y,\,Z)=0
$$
で表される（ただし$(X,Y,Z)$は平面上の点の座標）．

点$Q$は直線$AP$上にあり，かつ平面$\alpha$上にあるので，
直線$AP$を
$$
\overrightarrow{AQ}=t\,\overrightarrow{AP} \quad (t\in\mathbb{R})
$$
と表すと，$Q$が平面$\alpha$上にある条件は
$$
\overrightarrow{AP}\cdot \overrightarrow{OQ}=0
$$
である．

ここで
$$
\overrightarrow{OQ}
= \overrightarrow{OA}+\overrightarrow{AQ}
= -\overrightarrow{AO}+t\,\overrightarrow{AP}
$$
より
$$
\overrightarrow{AP}\cdot(-\overrightarrow{AO}+t\,\overrightarrow{AP})=0
$$
となる．展開すると
$$
-\overrightarrow{AP}\cdot\overrightarrow{AO}
+t\,|\overrightarrow{AP}|^2=0
$$
より
$$
t=\dfrac{\overrightarrow{AP}\cdot\overrightarrow{AO}}{|\overrightarrow{AP}|^2}
$$
である．

次に$\overrightarrow{AQ}$の大きさを求めると，
$$
|\overrightarrow{AQ}|
=|t|\,|\overrightarrow{AP}|
=\dfrac{|\overrightarrow{AP}\cdot\overrightarrow{AO}|}{|\overrightarrow{AP}|}
$$
したがって両辺を2乗して
$$
|\overrightarrow{AQ}|^2=
\dfrac{(\overrightarrow{AP}\cdot\overrightarrow{AO})^2}{|\overrightarrow{AP}|^2}
$$
となる．これを変形して
$$
(\overrightarrow{AP}\cdot\overrightarrow{AO})^2
=|\overrightarrow{AP}|^2\,|\overrightarrow{AQ}|^2
$$
が得られる．よって示された．

---

(2)  
(1)の結果を用いる．$|\overrightarrow{OQ}|=1$のときの点$P(x,y,0)$の軌跡を求める．

(1)の関係式から
$$
(\overrightarrow{AP}\cdot\overrightarrow{AO})^2
=|\overrightarrow{AP}|^2\,|\overrightarrow{AQ}|^2
$$
であるが，三角形$AOP$について
$$
\overrightarrow{AP}=\overrightarrow{AO}+\overrightarrow{OP}
$$
なので
$$
\overrightarrow{AP}\cdot\overrightarrow{AO}
=(\overrightarrow{AO}+\overrightarrow{OP})\cdot\overrightarrow{AO}
=|\overrightarrow{AO}|^2+\overrightarrow{OP}\cdot\overrightarrow{AO}
$$
となる．

実際に座標で計算すると，
$$
\overrightarrow{AP}\cdot\overrightarrow{AO}
=(x-a,\,y,\,-b)\cdot(-a,\,0,\,-b)
=-a(x-a)+b^2
=-ax+a^2+b^2
$$
また
$$
|\overrightarrow{AP}|^2=(x-a)^2+y^2+b^2,\quad
|\overrightarrow{AO}|^2=a^2+b^2
$$
である．

さらに$\overrightarrow{OQ}$は，点$O$から直線$AP$に下ろした垂線の足であるから，
三角形$AOQ$は直角三角形であり
$$
|\overrightarrow{AO}|^2
=|\overrightarrow{AQ}|^2+|\overrightarrow{OQ}|^2
$$
が成り立つ．与えられた条件 $|\overrightarrow{OQ}|=1$ を用いると
$$
|\overrightarrow{AQ}|^2=|\overrightarrow{AO}|^2-1=a^2+b^2-1
$$
となる．

これを(1)の式
$$
(\overrightarrow{AP}\cdot\overrightarrow{AO})^2
=|\overrightarrow{AP}|^2\,|\overrightarrow{AQ}|^2
$$
に代入すると
$$
(-ax+a^2+b^2)^2
=\bigl((x-a)^2+y^2+b^2\bigr)\,(a^2+b^2-1)
$$
を得る．

ここで$A=a^2+b^2$とおくと ($A>1$ である)，上式は
$$
(-ax+A)^2=\bigl((x-a)^2+y^2+b^2\bigr)\,(A-1)
$$
すなわち
$$
(ax-A)^2=(A-1)\bigl((x-a)^2+y^2+b^2\bigr)
$$
となる．左辺を展開すると
$$
(ax-A)^2=a^2x^2-2Aax+A^2
$$
右辺は
$$
(A-1)\bigl((x-a)^2+y^2+b^2\bigr)
=(A-1)\bigl(x^2-2ax+a^2+y^2+b^2\bigr)
$$
であるから，両辺を等しいとして整理する．

両辺を展開してまとめると，
まず $x^2$ の係数：
$$
a^2 - (A-1)=a^2-(a^2+b^2-1-1)=a^2-a^2-b^2+2=2-b^2
$$
（途中計算を丁寧にするため，実際には以下のように進める．）

右辺を展開する：
$$
(A-1)(x^2-2ax+a^2+y^2+b^2)
=(A-1)x^2-2a(A-1)x+(A-1)(a^2+y^2+b^2)
$$

したがって
$$
a^2x^2-2Aax+A^2
=(A-1)x^2-2a(A-1)x+(A-1)(a^2+y^2+b^2)
$$
両辺を左辺に移項すると
$$
(a^2-(A-1))x^2+(-2Aa+2a(A-1))x
+A^2-(A-1)(a^2+y^2+b^2)=0
$$
係数を順に計算する．

まず $x^2$ の係数：
$$
a^2-(A-1)
=a^2-(a^2+b^2-1)
=1-b^2
$$

次に $x$ の係数：
$$
-2Aa+2a(A-1)
=2a(-A+A-1)
=-2a
$$

定数項：
$$
A^2-(A-1)(a^2+y^2+b^2)
=A^2-(A-1)(A+y^2)
$$
ここで $A=a^2+b^2$ を用いた．
さらに
$$
(A-1)(A+y^2)=(A-1)A+(A-1)y^2
$$
なので
$$
A^2-(A-1)(A+y^2)=A^2-(A-1)A-(A-1)y^2
=A^2-A^2+A-(A-1)y^2
=A-(A-1)y^2
$$
よって全体として
$$
(1-b^2)x^2-2ax+A-(A-1)y^2=0
$$
ここで $A=a^2+b^2$ に戻して
$$
(1-b^2)x^2-2ax+(a^2+b^2)-(a^2+b^2-1)y^2=0
$$
すなわち
$$
(1-b^2)x^2-2ax+(a^2+b^2)-(a^2+b^2-1)y^2=0
$$
が得られる．

この式が，$|\overrightarrow{OQ}|=1$ をみたす点$P(x,y,0)$の軌跡である．

なお，$b^2\neq 1$ のときは $x^2$ と $y^2$ の係数を比較して，これは原点とずれた中心をもつ円または双曲線の方程式となる．  
ただし$b^2=1$ のときは $x^2$ の項が消え，$x$ について一次式となるため，この場合も上の式が軌跡を表す条件式として成り立つ．