## 解答

(1)  
条件  
$$x+y+z=1,\quad x+2y+3z=5$$  
より，2つの式の差をとると
$$
(x+2y+3z)-(x+y+z)=5-1
$$
すなわち
$$
y+2z=4
$$
を得る。  
ここで
$$
x+y+z=1 \quad\Rightarrow\quad x=1-y-z
$$
なので，$y$ を $z$ で表すと
$$
y=4-2z
$$
であり，
$$
x=1-y-z=1-(4-2z)-z=3z-3
$$
となる。したがって  
$x,y,z$ は任意の実数 $z$ に対して
$$
x=3z-3,\quad y=4-2z,\quad z=z
$$
と表される。

次に，よく知られた等式
$$
x^3+y^3+z^3-3xyz=(x+y+z)\bigl(x^2+y^2+z^2-xy-yz-zx\bigr)
$$
を用いる。ここで $x+y+z=1$ なので
$$
x^3+y^3+z^3-3xyz = x^2+y^2+z^2-xy-yz-zx
$$
と書ける。

右辺を $z$ の式で表す。  
まず
$$
x=3z-3,\quad y=4-2z
$$
より
\[
\begin{aligned}
x^2 &= (3z-3)^2 = 9z^2-18z+9,\\
y^2 &= (4-2z)^2 = 4z^2-16z+16,\\
z^2 &= z^2.
\end{aligned}
\]
したがって
$$
x^2+y^2+z^2 = (9z^2-18z+9)+(4z^2-16z+16)+z^2
           =14z^2-34z+25.
$$
また
\[
\begin{aligned}
xy &= (3z-3)(4-2z)
    = (3z)\cdot 4 + (3z)\cdot(-2z) + (-3)\cdot4 + (-3)\cdot(-2z) \\
   &= 12z-6z^2-12+6z
    = -6z^2+18z-12,\\
yz &= (4-2z)z = 4z-2z^2,\\
zx &= z(3z-3) = 3z^2-3z.
\end{aligned}
\]
よって
\[
\begin{aligned}
xy+yz+zx
&= (-6z^2+18z-12)+(4z-2z^2)+(3z^2-3z) \\
&= (-6z^2-2z^2+3z^2)+(18z+4z-3z)-12 \\
&= -5z^2+19z-12.
\end{aligned}
\]

したがって
\[
\begin{aligned}
x^3+y^3+z^3-3xyz
&= x^2+y^2+z^2-xy-yz-zx \\
&= (14z^2-34z+25) -(-5z^2+19z-12) \\
&= 14z^2-34z+25+5z^2-19z+12 \\
&= 19z^2-53z+37.
\end{aligned}
\]

これを $z$ についての2次関数とみなして最小値を求める。  
$$
f(z)=19z^2-53z+37
$$
とおくと，$a>0$ の2次関数 $az^2+bz+c$ の最小値は頂点の値
$$
\frac{4ac-b^2}{4a}
$$
で与えられることから，
\[
\begin{aligned}
\text{最小値} 
&= \frac{4\cdot 19\cdot 37 -(-53)^2}{4\cdot 19} \\
&= \frac{2812-2809}{76} \\
&= \frac{3}{76}.
\end{aligned}
\]

したがって，$x^3+y^3+z^3-3xyz$ の最小値は
$$
\frac{3}{76}
$$
である。

（補足）頂点の $z$ の値は
$$
z=\frac{53}{2\cdot 19}=\frac{53}{38}
$$
であるが，最小値を求めるだけなら上の計算で十分である。

---

(2)  
(1)と同様に，条件より
$$
x=3z-3,\quad y=4-2z
$$
と表される。ここで $z\ge 0$ のときの $xyz$ の最大値を考える。  

$$
xyz = (3z-3)(4-2z)z
$$
であるから
\[
\begin{aligned}
xyz 
&= z\{(3z-3)(4-2z)\} \\
&= z(-6z^2+18z-12) \quad (\text{(1) で求めた }xy)\\
&= -6z^3+18z^2-12z.
\end{aligned}
\]
そこで
$$
g(z)=-6z^3+18z^2-12z \quad (z\ge 0)
$$
とおく。

3次関数 $g(z)$ の極値を求めるため，微分を用いると
$$
g'(z) = -18z^2+36z-12.
$$
これを 0 とおくと
\[
\begin{aligned}
-18z^2+36z-12 &= 0 \\
\Leftrightarrow\quad 18z^2-36z+12 &=0 \\
\Leftrightarrow\quad 3z^2-6z+2 &=0.
\end{aligned}
\]
判別式を求めると
$$
(-6)^2-4\cdot 3\cdot 2=36-24=12
$$
であるから
\[
\begin{aligned}
z &= \frac{6\pm\sqrt{12}}{2\cdot 3}
   = \frac{6\pm 2\sqrt{3}}{6}
   = 1\pm\frac{\sqrt{3}}{3}.
\end{aligned}
\]
したがって $z\ge0$ の範囲での候補は
$$
z_1 = 1-\frac{\sqrt{3}}{3},\quad
z_2 = 1+\frac{\sqrt{3}}{3}.
$$

$z\ge 0$ において $g(z)$ が上に凸か下に凸か調べるため，
$$
g''(z) = -36z+36
$$
と2回微分すると，これは $z$ の増加とともに減少していく一次関数である。  
$z_1<z_2$ であり，$g'(z)$ の符号変化を調べると，3次関数の一般的性質より，
$z_1$ で極大，$z_2$ で極小となる（係数が $-6<0$ の3次関数なので $z\to\infty$ で $g(z)\to -\infty$）。  

したがって $z\ge0$ における $xyz=g(z)$ の最大値は $z=z_1=1-\dfrac{\sqrt{3}}{3}$ のときにとられる。  

よって，$z\ge 0$ のとき $xyz$ が最大となる $z$ の値は
$$
z = 1-\frac{\sqrt{3}}{3}
$$
である。