## 解答

直線 $l$ が $z$ 軸とねじれの位置にあるので，$l$ は $z$ 軸と交わらず，また平行でもない直線である．

ここで，$z$ 軸を通り，$z$ 軸に平行でない平面を1つとる．たとえば $x$ 軸，$y$ 軸，$z$ 軸をとり，$z$ 軸を含む任意の平面を考えると，その中で $z$ 軸に平行でない直線を1本選べば，その直線を含む平面は $z$ 軸を通り，かつ $z$ 軸に平行でない平面になる．

このようにして得られた平面を $\alpha$ とする．  
平面 $\alpha$ は $z$ 軸を含み，かつ $z$ 軸と平行でないから，$\alpha$ と直線 $l$ はねじれの位置にはならず，必ず1点で交わるか，あるいは平行となる．

しかし，$l$ は $z$ 軸とねじれの位置にあるので，$l$ は $z$ 軸に平行ではない．  
一方，$\alpha$ は $z$ 軸を含むが $z$ 軸に平行ではない平面なので，$l$ が $\alpha$ と平行であるならば，$l$ は $\alpha$ が含む $z$ 軸とも平行になってしまう．これは $l$ が $z$ 軸とねじれの位置にあることに反する．

したがって，$l$ は平面 $\alpha$ と平行ではなく，よって $l$ と平面 $\alpha$ はただ1点で交わる．  
その交点を $P$ とし，$z$ 軸と $l$ 上の点をそれぞれ $O$，$Q$ とする．

平面 $\alpha$ は $z$ 軸を含むから，点 $O$ と $P$ を通る直線 $OP$ は平面 $\alpha$ 内にある．また，$l$ は平面 $\alpha$ と交点 $P$ で交わるので，点 $P$ は $l$ 上にある．

ここで，直線 $OP$ と $l$ の両方に直交する直線を考える．ユークリッド空間では，2本の異なる直線 $OP$，$l$ を含む平面 $\alpha$ と，それに直交する直線はただ1本である（直線と平面の関係により，平面に垂直な直線は一点を通ってただ1本定まる）．

この直線は，平面 $\alpha$ に垂直であるから，平面 $\alpha$ 内の任意の直線と直交する．特に，平面 $\alpha$ 内の $z$ 軸とも直交する．また，この直線は $l$ を含む平面 $\alpha$ に垂直なので，$l$ とも直交する．

以上より，$l$ と $z$ 軸の両方に直交する直線が存在することが分かる．

次に，そのような直線がただ1つであることを示す．

$l$ と $z$ 軸の両方に直交する直線を $m$ とする．  
$m$ は $l$ に直交するから，$m$ は $l$ と交わる．交点を $R$ とする．また，$m$ は $z$ 軸にも直交するから，$m$ は $z$ 軸と交わり，その交点を $S$ とする．

すると，$R$ および $S$ は，それぞれ $l$ および $z$ 軸上の点であり，直線 $m$ は2点 $R, S$ を結ぶ直線であるから，$m$ は $l$ 上の点と $z$ 軸上の点とを結ぶ直線である．

一方，直線 $l$ と $z$ 軸に対し，それぞれに直交する共通の直線が2本あったとすると，これらはともに $l$ 上のある点と $z$ 軸上のある点とを結ぶ．しかし，ユークリッド空間では，2点を結ぶ直線はただ1本であるから，共通垂線はただ1本しか存在しない．

したがって，$l$ と $z$ 軸の両方に直交する直線はただ1つである．

よって，直線 $l$ と $z$ 軸の両方に直交する直線がただ1つ存在することが示された．