## 解答

(1)  
与えられた関数は  
$$
f(x)=2x^3-(6+3\sin a)x^2+(12\sin a)x+\sin^3 a+6\sin a+5
$$
である．

まず微分して極値を調べる．

$$
f'(x)=6x^2-2(6+3\sin a)x+12\sin a
$$

係数を整理すると

$$
f'(x)=6x^2-(12+6\sin a)x+12\sin a
$$

6で割ると

$$
f'(x)=6\left(x^2-(2+\sin a)x+2\sin a\right)
$$

となる．極値の候補は $f'(x)=0$ の解であるから，
$$
x^2-(2+\sin a)x+2\sin a=0
$$
を解く．判別式 $D$ は
$$
D=(2+\sin a)^2-4\cdot 2\sin a=4+4\sin a+\sin^2 a-8\sin a
=4-4\sin a+\sin^2 a
$$
であり，
$$
D=(\sin a-2)^2
$$
と変形できる．$\sin a$ は $-1\leq \sin a\leq 1$ であるから $\sin a-2\neq 0$ より $D>0$ であり，二次方程式は異なる2つの実数解をもつ．よって $f(x)$ は極値を2つもつことがわかる．

この2つの解を求めると，
$$
x=\frac{(2+\sin a)\pm|\sin a-2|}{2}.
$$

ここで $\sin a-2<0$ なので $|\sin a-2|=2-\sin a$ であるから，

- $x_1=\dfrac{(2+\sin a)+(2-\sin a)}{2}=\dfrac{4}{2}=2$  
- $x_2=\dfrac{(2+\sin a)-(2-\sin a)}{2}=\dfrac{2\sin a}{2}=\sin a$

となる．したがって $f'(x)=0$ となる点は $x=2$ と $x=\sin a$ の2点である．

どちらが極大でどちらが極小かを調べるために，二次導関数 $f''(x)$ を用いる．

$$
f'(x)=6x^2-(12+6\sin a)x+12\sin a
$$

を微分すると

$$
f''(x)=12x-(12+6\sin a)=12\left(x-\frac{1}{2}(1+\sin a)\right)
$$

となる．

$\sin a$ の範囲 $-1\leq \sin a\leq 1$ から $\sin a\leq 1$ であるので，
$$
\sin a \leq \frac{1}{2}(1+\sin a)\leq 1
$$
が成り立つ．左の不等式は
$$
\sin a \leq \frac{1}{2}(1+\sin a)\ \Longleftrightarrow\ 
2\sin a \leq 1+\sin a\ \Longleftrightarrow\ \sin a \leq 1
$$
より成り立ち，右の不等式は
$$
\frac{1}{2}(1+\sin a)\leq 1\ \Longleftrightarrow\ 1+\sin a\leq 2\ \Longleftrightarrow\ \sin a\leq 1
$$
より同様に成り立つ．

したがって
$$
\sin a \leq \frac{1}{2}(1+\sin a)\leq 1<2
$$
より
$$
\sin a < \frac{1}{2}(1+\sin a) < 2
$$
が成り立つ．これを用いて $f''(\sin a)$, $f''(2)$ の符号を見ると，

- $x=\sin a$ では
  $$
  f''(\sin a)=12\left(\sin a-\frac{1}{2}(1+\sin a)\right)
  =12\cdot\frac{\sin a-1}{2}=6(\sin a-1)\leq 0
  $$
  （$\sin a=1$ のときは $f''(\sin a)=0$ であるが，その場合も後述の符号変化から極大とわかる）．
- $x=2$ では
  $$
  f''(2)=12\left(2-\frac{1}{2}(1+\sin a)\right)
  >0
  $$
  である．

二次関数 $f'(x)$ の軸は $x=\dfrac{1}{2}(1+\sin a)$ であり，$\sin a < \dfrac{1}{2}(1+\sin a) < 2$ であるから，$f'(x)$ は $x=\sin a$ で $+$から$-$へ，$x=2$ で$-$から$+$へ符号が変化する．したがって

- $x=\sin a$ で $f(x)$ は極大
- $x=2$ で $f(x)$ は極小

となる．よって $f(x)$ はただ1つの極大値をもち，その極大値は $x=\sin a$ における $f(\sin a)$ である．

実際に $f(\sin a)$ を計算する．

$$
\begin{aligned}
f(\sin a)
&=2(\sin a)^3-(6+3\sin a)(\sin a)^2+(12\sin a)(\sin a)+\sin^3 a+6\sin a+5\\[2mm]
&=2\sin^3 a-(6+3\sin a)\sin^2 a+12\sin^2 a+\sin^3 a+6\sin a+5
\end{aligned}
$$

まず $\sin^3 a$ の項をまとめると

$$
2\sin^3 a+\sin^3 a=3\sin^3 a
$$

次に $\sin^2 a$ の係数をまとめると

$$
-(6+3\sin a)\sin^2 a+12\sin^2 a
=(-6-3\sin a+12)\sin^2 a
=(6-3\sin a)\sin^2 a
=3(2-\sin a)\sin^2 a
$$

よって

$$
f(\sin a)=3\sin^3 a+3(2-\sin a)\sin^2 a+6\sin a+5
$$

ここで $3\sin^3 a-3\sin^3 a=0$ を利用して整理すると

$$
3\sin^3 a+3(2-\sin a)\sin^2 a
=3\sin^3 a+6\sin^2 a-3\sin^3 a
=6\sin^2 a
$$

したがって

$$
f(\sin a)=6\sin^2 a+6\sin a+5
$$

となる．よって極大値 $M(a)$ は

$$
M(a)=6\sin^2 a+6\sin a+5
$$

である．

(2)  
(1)で求めた
$$
M(a)=6\sin^2 a+6\sin a+5
$$
を，$0\leq a<2\pi$ における $\sin a$ の範囲 $-1\leq \sin a\leq 1$ のもとで調べる．

$\sin a$ を一つの変数 $t$ とおき，
$$
t=\sin a\quad(-1\leq t\leq 1)
$$
とおくと，$M(a)$ は
$$
M(t)=6t^2+6t+5
$$
という $t$ の二次関数とみなせる．

この二次関数は $t^2$ の係数が $6>0$ なので上に凸であり，よって区間 $[-1,1]$ における最大値・最小値は，最小値が頂点で，最大値は端点 $t=-1$ または $t=1$ でとられる．

まず頂点の $t$ 座標は
$$
t=-\frac{6}{2\cdot 6}=-\frac{1}{2}
$$
で，これは $-1\leq -\dfrac{1}{2}\leq 1$ を満たすので区間内にある．

したがって，
- $t=-\dfrac{1}{2}$ で $M(t)$ は最小値，
- $t=-1,1$ のどちらかで最大値

をとる．具体的に値を計算する．

頂点での値：
$$
\begin{aligned}
M\!\left(-\frac{1}{2}\right)
&=6\left(-\frac{1}{2}\right)^2+6\left(-\frac{1}{2}\right)+5\\
&=6\cdot\frac{1}{4}-3+5\\
&=\frac{6}{4}+2\\
&=\frac{3}{2}+2\\
&=\frac{7}{2}
\end{aligned}
$$
よって最小値は $\dfrac{7}{2}$ である．

端点での値：
$$
M(-1)=6\cdot 1+6\cdot(-1)+5=6-6+5=5
$$

$$
M(1)=6\cdot 1+6\cdot 1+5=6+6+5=17
$$

したがって区間 $[-1,1]$ における最大値は $17$ である．

あとは，それぞれの値をとるときの $a$ を求める．

- 最小値 $\dfrac{7}{2}$ をとるのは $\sin a=-\dfrac{1}{2}$ のときである．  
  $0\leq a<2\pi$ において $\sin a=-\dfrac{1}{2}$ となる $a$ は
  $$
  a=\frac{7\pi}{6},\ \frac{11\pi}{6}
  $$
  である．

- 最大値 $17$ をとるのは $\sin a=1$ のときである．  
  $0\leq a<2\pi$ で $\sin a=1$ となる $a$ は
  $$
  a=\frac{\pi}{2}
  $$
  である．

まとめると，

- $0\leq a<2\pi$ における $M(a)$ の最大値は $17$，そのときの $a$ は $a=\dfrac{\pi}{2}$．
- $0\leq a<2\pi$ における $M(a)$ の最小値は $\dfrac{7}{2}$，そのときの $a$ は $a=\dfrac{7\pi}{6},\ \dfrac{11\pi}{6}$

となる．