## 解答

(1)  
$\overrightarrow{a}=\overrightarrow{OA}$，$\overrightarrow{b}=\overrightarrow{OB}$，$\overrightarrow{c}=\overrightarrow{OC}$，$\overrightarrow{x}=\overrightarrow{OP}$ とおく。

まず，${PA}^2$ をベクトルで表す。  
点 $P$ から点 $A$ へのベクトルは
$$
\overrightarrow{PA}=\overrightarrow{OA}-\overrightarrow{OP}
=\overrightarrow{a}-\overrightarrow{x}
$$
であるから，
$$
{PA}^2 = |\overrightarrow{PA}|^2
=|\overrightarrow{a}-\overrightarrow{x}|^2.
$$
一般にベクトル $\overrightarrow{u},\overrightarrow{v}$ に対して  
$|\overrightarrow{u}-\overrightarrow{v}|^2
=|\overrightarrow{u}|^2+|\overrightarrow{v}|^2-2\overrightarrow{u}\cdot\overrightarrow{v}$  
が成り立つので，これを用いると
$$
{PA}^2
=|\overrightarrow{a}|^2+|\overrightarrow{x}|^2
-2\overrightarrow{a}\cdot\overrightarrow{x}
$$
となる。同様にして
$$
\begin{aligned}
{PB}^2
&=|\overrightarrow{b}-\overrightarrow{x}|^2
=|\overrightarrow{b}|^2+|\overrightarrow{x}|^2-2\overrightarrow{b}\cdot\overrightarrow{x},\\
{PC}^2
&=|\overrightarrow{c}-\overrightarrow{x}|^2
=|\overrightarrow{c}|^2+|\overrightarrow{x}|^2-2\overrightarrow{c}\cdot\overrightarrow{x}
\end{aligned}
$$
である。

したがって
$$
\begin{aligned}
L
&={PA}^2+{PB}^2+{PC}^2 \\
&=\bigl(|\overrightarrow{a}|^2+|\overrightarrow{x}|^2
-2\overrightarrow{a}\cdot\overrightarrow{x}\bigr)
 +\bigl(|\overrightarrow{b}|^2+|\overrightarrow{x}|^2
-2\overrightarrow{b}\cdot\overrightarrow{x}\bigr) \\
&\quad
 +\bigl(|\overrightarrow{c}|^2+|\overrightarrow{x}|^2
-2\overrightarrow{c}\cdot\overrightarrow{x}\bigr) \\
&=(|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2)
+3|\overrightarrow{x}|^2
-2(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})\cdot\overrightarrow{x}.
\end{aligned}
$$

よって
$$
L
=3{|\overrightarrow{x}|}^2-
2(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})\cdot\overrightarrow{x}+
{|\overrightarrow{a}|}^2+
{|\overrightarrow{b}|}^2+
{|\overrightarrow{c}|}^2
$$
が示された。

---

(2)  
(1) の結果を用いる。$\overrightarrow{s}=\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c}$ とおくと
$$
L=3|\overrightarrow{x}|^2-2\overrightarrow{s}\cdot\overrightarrow{x}
+|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
$$
である。ここで
$$
3|\overrightarrow{x}|^2-2\overrightarrow{s}\cdot\overrightarrow{x}
$$
だけを平方完成する。

まず
$$
\left|\overrightarrow{x}-\frac{1}{3}\overrightarrow{s}\right|^2
=|\overrightarrow{x}|^2
-2\overrightarrow{x}\cdot\frac{1}{3}\overrightarrow{s}
+\left|\frac{1}{3}\overrightarrow{s}\right|^2
=|\overrightarrow{x}|^2-\frac{2}{3}\overrightarrow{s}\cdot\overrightarrow{x}
+\frac{1}{9}|\overrightarrow{s}|^2
$$
であるから，両辺を 3 倍すると
$$
3\left|\overrightarrow{x}-\frac{1}{3}\overrightarrow{s}\right|^2
=3|\overrightarrow{x}|^2-2\overrightarrow{s}\cdot\overrightarrow{x}
+\frac{1}{3}|\overrightarrow{s}|^2
$$
を得る。これを変形して
$$
3|\overrightarrow{x}|^2-2\overrightarrow{s}\cdot\overrightarrow{x}
=3\left|\overrightarrow{x}-\frac{1}{3}\overrightarrow{s}\right|^2
-\frac{1}{3}|\overrightarrow{s}|^2
$$
となる。

よって
$$
\begin{aligned}
L
&=3\left|\overrightarrow{x}-\frac{1}{3}\overrightarrow{s}\right|^2
-\frac{1}{3}|\overrightarrow{s}|^2
+|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2 \\
&=3\left|\overrightarrow{x}-\frac{1}{3}(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})\right|^2
+\left(
|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-\frac{1}{3}|\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c}|^2
\right).
\end{aligned}
$$

第 1 項 $3\left|\overrightarrow{x}-\frac{1}{3}(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})\right|^2$ はベクトルの長さの 2 乗であり，常に $0$ 以上である。したがって $L$ を最小にするのは
$$
\overrightarrow{x}-\frac{1}{3}(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})=\overrightarrow{0}
$$
すなわち
$$
\overrightarrow{x}=\frac{1}{3}(\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c})
$$
のときである。

ここで，$\overrightarrow{OG}=\dfrac{1}{3}(\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC})$ なる点 $G$ は三角形 $ABC$ の重心であるという性質を用いると，$P$ は三角形 $ABC$ の重心 $G$ であることが分かる。

次に，このときの $L$ の最小値を求める。最小値は上の式で第 1 項が $0$ となるときの第 2 項に等しいから
$$
L_{\min}
=|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-\frac{1}{3}|\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c}|^2
$$
である。右辺を三角形の辺の長さで表す。

まず
$$
|\overrightarrow{a}+\overrightarrow{b}+\overrightarrow{c}|^2
=|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
+2(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a})
$$
なので
$$
\begin{aligned}
L_{\min}
&=|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-\frac{1}{3}
\Bigl(
|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
+2(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a})
\Bigr) \\
&=\frac{2}{3}
\bigl(|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2\bigr)
-\frac{2}{3}
(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a}) \\
&=\frac{2}{3}
\Bigl(
|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a})
\Bigr).
\end{aligned}
$$

ここで三角形の辺の長さの 2 乗をベクトルで表す。  
$\overrightarrow{AB}=\overrightarrow{b}-\overrightarrow{a}$ だから
$$
\begin{aligned}
{AB}^2
&=|\overrightarrow{AB}|^2
=|\overrightarrow{b}-\overrightarrow{a}|^2 \\
&=|\overrightarrow{a}|^2+|\overrightarrow{b}|^2
-2\overrightarrow{a}\cdot\overrightarrow{b}
\end{aligned}
$$
同様に
$$
\begin{aligned}
{BC}^2
&=|\overrightarrow{c}-\overrightarrow{b}|^2
=|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-2\overrightarrow{b}\cdot\overrightarrow{c},\\
{CA}^2
&=|\overrightarrow{a}-\overrightarrow{c}|^2
=|\overrightarrow{c}|^2+|\overrightarrow{a}|^2
-2\overrightarrow{c}\cdot\overrightarrow{a}.
\end{aligned}
$$

これらを足し合わせると
$$
\begin{aligned}
{AB}^2+{BC}^2+{CA}^2
&=2(|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2)
-2(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a}) \\
&=2\Bigl(
|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a})
\Bigr).
\end{aligned}
$$

したがって
$$
\frac{1}{3}({AB}^2+{BC}^2+{CA}^2)
=\frac{2}{3}
\Bigl(
|\overrightarrow{a}|^2+|\overrightarrow{b}|^2+|\overrightarrow{c}|^2
-(\overrightarrow{a}\cdot\overrightarrow{b}
+\overrightarrow{b}\cdot\overrightarrow{c}
+\overrightarrow{c}\cdot\overrightarrow{a})
\Bigr)
=L_{\min}
$$
となる。

ゆえに，$L$ を最小にする点 $P$ は三角形 $ABC$ の重心であり，そのときの最小値は
$$
\frac{1}{3}({AB}^2+{BC}^2+{CA}^2)
$$
である。